### PR TITLE
[WIP] refactor: rename one-word component name

### LINKED ISSUE #23: Avoid using one-word name for components
Respect [style guide](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential)

### PR DESCRIPTION
**Pull request by mutoe**
close #23

### CODE REVIEW

**Comment by mutoe** [comment]
@levchak0910 Do we need to rename `index.vue` file in component folder? like `src/components/Article/index.vue` to `src/components/Article/ArticleDetail.vue` ?

**Comment by levchak0910** [comment]
Let's make the components folder plain (as you have made previously)
I'm not very comfortable with this, but it's best to stick with the official vue style guide.

**Comment by mutoe** [comment]
@levchak0910  I'll leave the rest to you, my friend

**Comment by levchak0910** [comment]
@mutoe ok, thanks)

**Review by levchak0910 — APPROVED** [review]

**Pull request merged**
